--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hebbinkpro/pmmp-webserver
build-by-default: true
branches:
- main
projects:
  pmmp-webserver:
    path: ""
    model: virion
    type: library
...
